### ISSUE TITLE
Bindings for material-ui-icons

### ISSUE THREAD

**Issue by kdkeyser** [jsiebern/bs-material-ui#30]
Just wanted to double check that I am not missing anything: at the moment, bs-material-ui does not include bindings to the Material-ui-icons, right? (i.e. https://github.com/mui-org/material-ui/tree/master/packages/material-ui-icons )

Do you consider this as something you want to add later, of something better suited for a stand-alone package? If there is interest to add this, I will try and have a look to see if the codegen approach you used would work to generate these bindings as well.

My main goal is converting some of the Material-UI docs and code examples to ReasonML, and the icons + theme support seem to be the main showstoppers right now.

**Comment by jsiebern** [comment]
It's not too big of a deal to add them to the bindings, I just wasn't sure yet if they'd belong as they are a separate package by themselves as well. But there's probably no harm in adding them as a peer dep and including them in the bindings.

Most theming works btw, theres just one manual binding you need to add:

```ml
[@bs.module "@material-ui/core/styles"]
external createMuiTheme: Js.t({..}) => Js.t({..}) = "createMuiTheme";
let theme =
  createMuiTheme({
    "palette": {
      "primary": {
        "main": "#3facff",
      },
      "secondary": {
        "main": "#ff823f",
      },
    },
});

/* ... */

<MaterialUi_MuiThemeProvider theme={`ObjectGeneric(theme)}>
    <div />
</MaterialUi_MuiThemeProvider>
```

**Comment by kdkeyser** [comment]
Thanks for the info. Sounds like the remaining effort is quite doable, so I am giving it a go.

I started looking at reason-mui-binding-generator, but ran into some issues. I suspect that the README is a bit out of date, since there is no longer an env.example.js file, and no scripts folder. I changed the included env.js file in extract/src, and also modified package.json in the extract subdir (the copy script also has a reference to the material-ui path that needs to be modified)

After that, I assumed I needed to do yarn install in the root, and yarn install; yarn copy; yarn extract in the extract folder, but that gives errors:

`Error parsing src for /home/developer/shared/reason-mui-binding-generator/extract/core/ButtonBase/TouchRipple.js
/home/developer/shared/reason-mui-binding-generator/extract/src/extract.js:64
    throw err;
    ^

SyntaxError: Unexpected token (168:46)
    at Parser.pp.raise (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExprAtom (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/expression.js:425:12)
    at Parser.parseExprAtom (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOp (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/expression.js:188:42)
    at Parser.pp.parseExprOp (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/expression.js:190:19)
    at Parser.pp.parseExprOps (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/expression.js:167:17)
    at Parser.pp.parseMaybeConditional (/home/developer/shared/reason-mui-binding-generator/extract/node_modules/babylon/lib/parser/expression.js:145:19)
error Command failed with exit code 1.
`
The token it fails on is `**`

Anything obvious that I am missing?

**Comment by jsiebern** [comment]
You're not missing something obvious, I couldn't get babel to transpile `**` for the life of me (or rather for time I have maintaining this project on the side).

What you need to to is manually run a search and replace inside the `extract/core` folder (replace `**` simply by `*` for example). After you've done this the `yarn extract` inside the `extract` folder should work.

I really need to clean up that repo 😅

**Comment by kdkeyser** [comment]
I created a pull request for the bindings generator repo which fixes the issue with `**` and also reflects the changes in the process of generating the bindings in the README.

Started looking into generating the bindings for the icons as well, but react-docgen seems to have issues with the js modules for the icons (they are not identified as React modules). Will have a closer look. Maybe the js modules for the icons provide functions that need to be applied first to obtain the React modules.

**Comment by jsiebern** [comment]
@kdkeyser I've seen it, thanks so much, I'll merge it tomorrow! As for the icons: I believe that it is more than sufficient to just read the file names and generate the modules from the existing `Icon` module. A little like I did for the colors but with an actual react module underneath.
